#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.arm.elf.M3{1,0,15.12,1
#
flash_debug.xem3: package/cfg/flash_debug.xem3.mak

clean::
	-$(RM) package/cfg/flash_debug.xem3.mak
